In [1]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
import pandas as pd

In [4]:
url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'100',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': XXXX,
}

session = Session()
session.headers.update(headers)

try:
    response = session.get(url, params=parameters)
    data = json.loads(response.text)
    #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
    print(e)

### BTCUSD

In [31]:
pd.DataFrame(data['data'][0]['quote']).transpose()

,last_updated,market_cap,percent_change_1h,percent_change_24h,percent_change_30d,percent_change_60d,percent_change_7d,percent_change_90d,price,volume_24h
USD,2021-06-17T13:15:02.000Z,7.25708e+11,-0.416163,-0.679412,-11.6,-29.613,2.54245,-33.8959,38731.1,3.84039e+10

### ETHUSD

In [32]:
pd.DataFrame(data['data'][1]['quote']).transpose()

,last_updated,market_cap,percent_change_1h,percent_change_24h,percent_change_30d,percent_change_60d,percent_change_7d,percent_change_90d,price,volume_24h
USD,2021-06-17T13:15:02.000Z,2.77241e+11,-0.82538,-2.3276,-29.7593,12.5013,-6.48827,31.6098,2383.27,2.26701e+10

In [30]:
pd.DataFrame(data['data'])

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,platform,cmc_rank,last_updated,quote
0,1,Bitcoin,BTC,bitcoin,9093,2013-04-28T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.873707e+07,1.873707e+07,None,1,2021-06-17T13:15:02.000Z,"{'USD': {'price': 38731.148044868634, 'volume_..."
1,1027,Ethereum,ETH,ethereum,5815,2015-08-07T00:00:00.000Z,"[mineable, pow, smart-contracts, ethereum, coi...",NaN,1.163276e+08,1.163276e+08,None,2,2021-06-17T13:15:02.000Z,"{'USD': {'price': 2383.274490756754, 'volume_2..."
2,825,Tether,USDT,tether,12871,2015-02-25T00:00:00.000Z,"[payments, stablecoin, stablecoin-asset-backed...",NaN,6.255085e+10,6.447177e+10,"{'id': 1027, 'name': 'Ethereum', 'symbol': 'ET...",3,2021-06-17T13:14:08.000Z,"{'USD': {'price': 1.000157972655, 'volume_24h'..."
3,1839,Binance Coin,BNB,binance-coin,526,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",1.705328e+08,1.534329e+08,1.694329e+08,None,4,2021-06-17T13:14:07.000Z,"{'USD': {'price': 353.9722118940683, 'volume_2..."
4,2010,Cardano,ADA,cardano,255,2017-10-01T00:00:00.000Z,"[mineable, dpos, pos, platform, research, smar...",4.500000e+10,3.194633e+10,3.270489e+10,None,5,2021-06-17T13:14:09.000Z,"{'USD': {'price': 1.498079461829, 'volume_24h'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1042,Siacoin,SC,siacoin,51,2015-08-26T00:00:00.000Z,"[mineable, pow, blake2b, platform, distributed...",NaN,4.806929e+10,4.806929e+10,None,96,2021-06-17T13:15:02.000Z,"{'USD': {'price': 0.0151560334658, 'volume_24h..."
96,1808,OMG Network,OMG,omg,253,2017-07-14T00:00:00.000Z,"[medium-of-exchange, payments, state-channels,...",1.402454e+08,1.402454e+08,1.402454e+08,None,97,2021-06-17T13:14:08.000Z,"{'USD': {'price': 5.18265271573975, 'volume_24..."
97,2087,KuCoin Token,KCS,kucoin-token,33,2017-10-24T00:00:00.000Z,"[marketplace, centralized-exchange, discount-t...",1.701186e+08,8.011864e+07,1.701186e+08,"{'id': 1027, 'name': 'Ethereum', 'symbol': 'ET...",98,2021-06-17T13:15:02.000Z,"{'USD': {'price': 8.93296190702047, 'volume_24..."
98,2099,ICON,ICX,icon,65,2017-10-27T00:00:00.000Z,"[platform, enterprise-solutions, interoperabil...",NaN,6.343383e+08,8.004600e+08,None,99,2021-06-17T13:15:02.000Z,"{'USD': {'price': 1.12727194656547, 'volume_24..."
99,4779,HUSD,HUSD,husd,76,2019-10-15T00:00:00.000Z,"[pow, medium-of-exchange, stablecoin, stableco...",NaN,6.777606e+08,6.777606e+08,"{'id': 1027, 'name': 'Ethereum', 'symbol': 'ET...",100,2021-06-17T13:14:09.000Z,"{'USD': {'price': 1.00002982378944, 'volume_24..."